### ISSUE TITLE
help me plesase

### ISSUE THREAD

**Issue by Znagling** [theslavicbear/Ebook-Publisher#71]
I'm a complete zero in python. I downloaded the archive with your script, unpacked it, and run Ebook-Publisher.py the command prompt opens for a second and closes immediately. What do I need to do so that I can use your script?

**Comment by theslavicbear** [comment]
This is a command-line utility. Running it without providing any arguments will not do anything. You need to open the command prompt and navigate to the folder with Ebook-Publisher.py file and run it with python 3 like such:
`python3 Ebook-Publisher.py`
You may need to replace "python3" with the exact file path of your python3 executable, but since you were able to run by double-clicking it or however, this shouldn't be necessary. Also, if you run from the command prompt you will get the chance to read any output before the window closes. You must add at least one URL to the command after "Ebook-Publisher.py" for it to download anything. You can check the README file or add `-h` option and run to get instructions on adding arguments.

If you are command-line averse, you can write your command into a text file and change the extension from ".txt" to ".bat" and run that instead. If you take this approach, add `pause` to the end of the batch script so the command prompt stays open after executing.
